ManagementProject/Models/ProjectCondition.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ManagementProject.Models
{
    [Table("R_PROJECT_CONDITION")]
    public class ProjectCondition : Global
    {
        [Key]
        [Required]
        [StringLength(40, MinimumLength = 5)]
        [DisplayName("Condition Type")]
        public string CONDITION_TYPE { get; set; }
        [Required]
        [DisplayName("Abbreviation")]
        [StringLength(12, MinimumLength = 5)]
        public string ABBREVIATION { get; set; }
        [Required]
        [DisplayName("Long Name")]
        [StringLength(30, MinimumLength = 5)]
        public string LONG_NAME { get; set; }
        [Required]
        [DisplayName("Short Name")]
        [StringLength(40, MinimumLength = 5)]
        public string SHORT_NAME { get; set; }
        [DisplayName("Project Type")]
        public string PROJECT_TYPE { get; set; }
    }
}

ManagementProject/Controllers/ProjectConditionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ManagementProject.Models;

namespace ManagementProject.Controllers
{
    public class ProjectConditionsController : Controller
    {
        private readonly ManProContext _context;

        public ProjectConditionsController(ManProContext context)
        {
            _context = context;
        }

        // GET: ProjectConditions
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProjectCondition.ToListAsync());
        }

        // GET: ProjectConditions/Create
        public IActionResult Create()
        {
            ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");
            ViewBag.ListProjectType = new SelectList(_context.ProjectType, "PROJECT_TYPE", "ABBREVIATION");

            return View();
        }

        // POST: ProjectConditions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CONDITION_TYPE,ABBREVIATION,LONG_NAME,SHORT_NAME,PROJECT_TYPE,SOURCEID")] ProjectCondition projectCondition)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    projectCondition.ROW_CREATED_BY = "SYSTEM ADD";

                    _context.Add(projectCondition);
                    await _context.SaveChangesAsync();

                    TempData["resultTrans"] = new Dictionary<string, string>()
                    {
                        { "1", "0" },
                        { "2", "I" },
                        { "3", projectCondition.CONDITION_TYPE }
                    };

                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    TempData["resultTrans"] = new Dictionary<string, string>()
                    {
                        { "1", "1" },
                        { "2", "I" },
                        { "3", ex.Message }
                    };

                    ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");
                    ViewBag.ListProjectType = new SelectList(_context.ProjectType, "PROJECT_TYPE", "ABBREVIATION");

                    return View();
                }
            }
            return View(projectCondition);
        }

        // GET: ProjectConditions/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
                return NotFound();

            var projectCondition = await _context.ProjectCondition.FindAsync(id);
            if (projectCondition == null)
                return NotFound();

            ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");
            ViewBag.ListProjectType = new SelectList(_context.ProjectType, "PROJECT_TYPE", "ABBREVIATION");

            return View(projectCondition);
        }

        // POST: ProjectConditions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CONDITION_TYPE,ABBREVIATION,LONG_NAME,SHORT_NAME,PROJECT_TYPE,SOURCEID")] ProjectCondition projectCondition)
        {
            if (id != projectCondition.CONDITION_TYPE)
                return NotFound();

            if (_context.ProjectCondition.Find(id) == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var local = _context.Set<ProjectCondition>()
                       .Local
                       .FirstOrDefault(x => x.CONDITION_TYPE.Equals(id));

                    local.SOURCEID = projectCondition.SOURCEID;
                    local.PROJECT_TYPE = projectCondition.PROJECT_TYPE;
                    local.ABBREVIATION = projectCondition.ABBREVIATION;
                    local.SHORT_NAME = projectCondition.SHORT_NAME;
                    local.LONG_NAME = projectCondition.LONG_NAME;
                    local.REMARK = projectCondition.REMARK;

                    local.ROW_CHANGED_BY = "SYSTEM EDIT";

                    _context.Update(local);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectConditionExists(projectCondition.CONDITION_TYPE))
                        return NotFound();
                    else
                        throw;
                }

                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "0" },
                    { "2", "U" },
                    { "3", projectCondition.CONDITION_TYPE }
                };

                return RedirectToAction(nameof(Index));
            }
            return View(projectCondition);
        }

        // GET: ProjectConditions/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "1" },
                    { "2", "D" },
                    { "3", $"Your parameter id is null." }
                };
                return View();
            }

            var projectCondition = await _context.ProjectCondition
                .FirstOrDefaultAsync(m => m.CONDITION_TYPE == id);

            if (projectCondition == null)
            {
                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "1" },
                    { "2", "D" },
                    { "3", $"ID key : {id}, not found." }
                };
                return View();
            }

            projectCondition = await _context.ProjectCondition.FindAsync(id);
            _context.ProjectCondition.Remove(projectCondition);
            await _context.SaveChangesAsync();

            TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "0" },
                    { "2", "D" },
                    { "3", projectCondition.CONDITION_TYPE }
                };

            return RedirectToAction(nameof(Index));
        }

        private bool ProjectConditionExists(string id)
        {
            return _context.ProjectCondition.Any(e => e.CONDITION_TYPE == id);
        }
    }
}

ManagementProject/Views/ProjectConditions/Create.cshtml
@model ManagementProject.Models.ProjectCondition
<!-- Page content -->
<div class="page-content w-75">
    <!-- Main content -->
    <div class="content-wrapper">
        <!-- Content area -->
        <div class="content">
            <!-- Form inputs -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h5 class="card-title">Project Condtion form Input</h5>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="remove" asp-action="Index" asp-controller="ProjectConditions"></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Create", "ProjectConditions", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <fieldset>
                            <legend class="font-weight-semibold text-uppercase font-size-sm">Enter Project Condition information:</legend>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Select reference sources:</label>
                                <div class="col-md-6">
                                    @Html.DropDownListFor(x => x.SOURCEID, (IEnumerable<SelectListItem>)ViewBag.ListSource, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Search Project Type:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.DropDownListFor(x => x.PROJECT_TYPE, (IEnumerable<SelectListItem>)ViewBag.ListProjectType, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Condition Type:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.CONDITION_TYPE, new { @class = "form-control", @placeholder = "Condition Type" })
                                    <div class="form-control-feedback">
                                        <i id="condtype-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.CONDITION_TYPE, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter abbreviation:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.ABBREVIATION, new { @class = "form-control", @placeholder = "Abbreviation" })
                                    <div class="form-control-feedback">
                                        <i id="abbr-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.ABBREVIATION, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter long name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.LONG_NAME, new { @class = "form-control", @placeholder = "Long Name" })
                                    <div class="form-control-feedback">
                                        <i id="long-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.LONG_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter short name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.SHORT_NAME, new { @class = "form-control", @placeholder = "Short Name" })
                                    <div class="form-control-feedback">
                                        <i id="short-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.SHORT_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend></legend>
                            <div class="form-group row">
                                <div class="text-right col-md-12">
                                    <button type="submit" class="btn bg-teal">Submit form <i class="icon-paperplane ml-2"></i></button>
                                </div>
                            </div>
                        </fieldset>
                    }
                </div>
            </div>
            <!-- /form inputs -->
            <partial name="~/Views/Shared/_app-trans-message.cshtml" />
            <partial view-data="ViewData" name="~/Views/Shared/_information_entry.cshtml" />
        </div>
    </div>
</div>
<script src="~/scripts/InternalCUD.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ManagementProject/Views/ProjectConditions/Edit.cshtml
@model ManagementProject.Models.ProjectCondition
<!-- Page content -->
<div class="page-content w-75">
    <!-- Main content -->
    <div class="content-wrapper">
        <!-- Content area -->
        <div class="content">

            <!-- Form inputs -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h5 class="card-title">Project Condition form Edit</h5>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="remove" asp-action="Index" asp-controller="ProjectConditions"></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Edit", "ProjectConditions", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <input type="hidden" asp-for="CONDITION_TYPE" />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <fieldset>
                            <legend class="font-weight-semibold text-uppercase font-size-sm">Enter Project Condition information:</legend>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Select reference sources:</label>
                                <div class="col-md-6">
                                    @Html.DropDownListFor(x => x.SOURCEID, (IEnumerable<SelectListItem>)ViewBag.ListSource, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Search Project Plan:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.DropDownListFor(x => x.PROJECT_TYPE, (IEnumerable<SelectListItem>)ViewBag.ListProjectType, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter abbreviation:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.ABBREVIATION, new { @class = "form-control", @placeholder = "Abbreviation" })
                                    <div class="form-control-feedback">
                                        <i id="abbr-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.ABBREVIATION, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter long name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.LONG_NAME, new { @class = "form-control", @placeholder = "Long Name" })
                                    <div class="form-control-feedback">
                                        <i id="long-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.LONG_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter short name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.SHORT_NAME, new { @class = "form-control", @placeholder = "Short Name" })
                                    <div class="form-control-feedback">
                                        <i id="short-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.SHORT_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend></legend>
                            <div class="form-group row">
                                <div class="text-right col-md-12">
                                    <button type="submit" class="btn bg-teal">Submit form <i class="icon-paperplane ml-2"></i></button>
                                </div>
                            </div>
                        </fieldset>
                    }
                </div>
            </div>
            <!-- /form inputs -->
            <partial name="~/Views/Shared/_information_entry.cshtml" />
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ManagementProject/Views/ProjectConditions/Index.cshtml
@model IEnumerable<ManagementProject.Models.ProjectCondition>
<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">List Project Conditions</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                <a class="list-icons-item" data-action="reload" asp-action="Index"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="float-right">
                    <button onclick="location.href='@Url.Action("Create","ProjectConditions")'"
                            class="ui-button jui-button bg-green border-green" data-fouc>
                        <i class="icon-plus3 mr-1"></i> New Project Condition
                    </button>
                </div>
            </div>
        </div>
        @using (Html.BeginForm())
        {
            <table class="table datatable-basic">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CONDITION_TYPE)</th>
                        <th>@Html.DisplayNameFor(model => model.PROJECT_TYPE)</th>
                        <th>@Html.DisplayNameFor(model => model.SOURCEID)</th>
                        <th>@Html.DisplayNameFor(model => model.ABBREVIATION)</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.CONDITION_TYPE)</td>
                                <td>@Html.DisplayFor(modelItem => item.PROJECT_TYPE)</td>
                                <td>@Html.DisplayFor(modelItem => item.SOURCEID)</td>
                                <td>@Html.DisplayFor(modelItem => item.ABBREVIATION)</td>
                                <td class="text-center">
                                    <div class="list-icons">
                                        <div class="dropdown">
                                            <a href="#" class="list-icons-item" data-toggle="dropdown">
                                                <i class="icon-menu9"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href="@Url.Action("Edit","ProjectConditions",new { id = item.CONDITION_TYPE})" class="dropdown-item">Edit <i class="fa fa-edit mr-1"></i></a>
                                                <a href="#modal_backdrop" id="mydel" data-toggle="modal" onclick="return getTitleRow(this);" class="dropdown-item">Delete <i class="icon-trash mr-1"></i></a>
                                                @Html.Hidden(item.CONDITION_TYPE) @Html.Hidden(Url.Action("Delete", "ProjectConditions", new { id = item.CONDITION_TYPE }))
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        }
    </div>
</div>
<script src="~/scripts/InternalCUD.js"></script>
<partial name="~/Views/Shared/_delete-screen.cshtml" />
<partial name="~/Views/Shared/_app-trans-message.cshtml" view-data="ViewData" />