ManagementProject/Models/ProjectPlan.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ManagementProject.Models
{
    [Table("PROJECT_PLAN")]
    public class ProjectPlan : Global
    {
        [Key]
        [Required]
        [StringLength(40, MinimumLength = 5)]
        [DisplayName("Plan ID")]
        public string PROJECT_PLAN_ID { get; set; }
        [Required]
        [StringLength(240, MinimumLength = 10)]
        [DisplayName("Description")]
        public string DESCRIPTION { get; set; }
        [Required]
        [StringLength(255, MinimumLength = 10)]
        [DisplayName("Plan Name")]
        public string PLAN_NAME { get; set; }
        [ForeignKey("PROJECT_TYPE")]
        [DisplayName("Project Type")]
        public string PROJECT_TYPE { get; set; }
    }
}

ManagementProject/Controllers/ProjectPlansController.cs
using ManagementProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ManagementProject.Controllers
{
    public class ProjectPlansController : Controller
    {
        private readonly ManProContext _context;

        public ProjectPlansController(ManProContext context)
        {
            _context = context;
        }

        // GET: ProjectPlans
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProjectPlan.ToListAsync());
        }

        // GET: ProjectPlans/Create
        public IActionResult Create()
        {
            ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");
            ViewBag.ListProjectType = new SelectList(_context.ProjectType, "PROJECT_TYPE", "ABBREVIATION");
            return View();
        }

        // POST: ProjectPlans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PROJECT_PLAN_ID,DESCRIPTION,PLAN_NAME,PROJECT_TYPE,REMARK,SOURCEID")] ProjectPlan projectPlan)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    projectPlan.ROW_CREATED_BY = "SYSTEM ADD";

                    _context.Add(projectPlan);
                    await _context.SaveChangesAsync();

                    TempData["resultTrans"] = new Dictionary<string, string>()
                    {
                        { "1", "0" },
                        { "2", "I" },
                        { "3", projectPlan.PROJECT_PLAN_ID }
                    };

                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    TempData["resultTrans"] = new Dictionary<string, string>()
                    {
                        { "1", "1" },
                        { "2", "I" },
                        { "3", ex.Message }
                    };

                    ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");
                    ViewBag.ListProjectType = new SelectList(_context.ProjectType, "PROJECT_TYPE", "ABBREVIATION");

                    return View();
                }
            }
            return View(projectPlan);
        }

        // GET: ProjectPlans/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
                return NotFound();

            var projectPlan = await _context.ProjectPlan.FindAsync(id);
            if (projectPlan == null)
                return NotFound();

            ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");
            ViewBag.ListProjectType = new SelectList(_context.ProjectType, "PROJECT_TYPE", "ABBREVIATION");

            return View(projectPlan);
        }

        // POST: ProjectPlans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("PROJECT_PLAN_ID,DESCRIPTION,PLAN_NAME,PROJECT_TYPE,REMARK,SOURCEID")] ProjectPlan projectPlan)
        {
            if (id != projectPlan.PROJECT_PLAN_ID)
                return NotFound();

            if (_context.ProjectPlan.Find(id) == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var local = _context.Set<ProjectPlan>()
                        .Local
                        .FirstOrDefault(x => x.PROJECT_PLAN_ID.Equals(id));

                    local.SOURCEID = projectPlan.SOURCEID;
                    local.PROJECT_TYPE = projectPlan.PROJECT_TYPE;
                    local.PLAN_NAME = projectPlan.PLAN_NAME;
                    local.DESCRIPTION = projectPlan.DESCRIPTION;
                    local.REMARK = projectPlan.REMARK;

                    local.ROW_CHANGED_BY = "SYSTEM EDIT";

                    _context.Update(local);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectPlanExists(projectPlan.PROJECT_PLAN_ID))
                        return NotFound();
                    else
                        throw;
                }

                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "0" },
                    { "2", "U" },
                    { "3", projectPlan.PROJECT_PLAN_ID }
                };

                return RedirectToAction(nameof(Index));
            }
            return View(projectPlan);
        }

        // GET: ProjectPlans/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "1" },
                    { "2", "D" },
                    { "3", $"Your parameter id is null." }
                };
                return View();
            }

            var projplan = await _context.ProjectPlan
                .FirstOrDefaultAsync(m => m.PROJECT_PLAN_ID == id);

            if (projplan == null)
            {
                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "1" },
                    { "2", "D" },
                    { "3", $"ID key : {id}, not found." }
                };
                return View();
            }

            projplan = await _context.ProjectPlan.FindAsync(id);
            _context.ProjectPlan.Remove(projplan);
            await _context.SaveChangesAsync();

            TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "0" },
                    { "2", "D" },
                    { "3", projplan.PROJECT_PLAN_ID }
                };

            return RedirectToAction(nameof(Index));
        }

        private bool ProjectPlanExists(string id)
        {
            return _context.ProjectPlan.Any(e => e.PROJECT_PLAN_ID == id);
        }
    }
}

ManagementProject/Views/ProjectPlans/Create.cshtml
@model ManagementProject.Models.ProjectPlan

<!-- Page content -->
<div class="page-content w-75">
    <!-- Main content -->
    <div class="content-wrapper">
        <!-- Content area -->
        <div class="content">
            <!-- Form inputs -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h5 class="card-title">Project Plan form Input</h5>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="remove" asp-action="Index" asp-controller="ProjectPlans"></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Create", "ProjectPlans", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <fieldset>
                            <legend class="font-weight-semibold text-uppercase font-size-sm">Enter Project Plan information:</legend>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Select reference sources:</label>
                                <div class="col-md-6">
                                    @Html.DropDownListFor(x => x.SOURCEID, (IEnumerable<SelectListItem>)ViewBag.ListSource, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Select reference Project Type:</label>
                                <div class="col-md-6">
                                    @Html.DropDownListFor(x => x.PROJECT_TYPE, (IEnumerable<SelectListItem>)ViewBag.ListProjectType, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Project Plan ID:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.PROJECT_PLAN_ID, new { @class = "form-control", @placeholder = "Project Plan ID" })
                                    <div class="form-control-feedback">
                                        <i id="projplan-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.PROJECT_PLAN_ID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Plan name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.PLAN_NAME, new { @class = "form-control", @placeholder = "Plan Name" })
                                    <div class="form-control-feedback">
                                        <i id="projplanname-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.PLAN_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Description:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextAreaFor(x => x.DESCRIPTION, new { @class = "form-control", @rows = "5", @cols = "5", @placeholder = "Enter your description Plan Name" })
                                    <div class="form-control-feedback">
                                        <i id="projdesc-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-3 col-form-label">Enter remark:</label>
                                <div class="col-md-9 form-group-feedback-right">
                                    @Html.TextAreaFor(x => x.REMARK, new { @class = "form-control", @rows = "5", @cols = "5", @placeholder = "Enter your description here" })
                                    <div class="form-control-feedback">
                                        <i id="remark-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend></legend>
                            <div class="form-group row">
                                <div class="text-right col-md-12">
                                    <button type="submit" class="btn bg-teal">Submit form <i class="icon-paperplane ml-2"></i></button>
                                </div>
                            </div>
                        </fieldset>
                    }
                </div>
            </div>
            <!-- /form inputs -->
            <partial name="~/Views/Shared/_app-trans-message.cshtml" />
            <partial view-data="ViewData" name="~/Views/Shared/_information_entry.cshtml" />
        </div>
    </div>
</div>

<script src="~/scripts/InternalCUD.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ManagementProject/Views/ProjectPlans/Edit.cshtml
@model ManagementProject.Models.ProjectPlan

<!-- Page content -->
<div class="page-content w-75">
    <!-- Main content -->
    <div class="content-wrapper">
        <!-- Content area -->
        <div class="content">

            <!-- Form inputs -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h5 class="card-title">Project Plan form Edit</h5>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="remove" asp-action="Index" asp-controller="ProjectPlans"></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Edit", "ProjectPlans", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <input type="hidden" asp-for="PROJECT_PLAN_ID" />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <fieldset>
                            <legend class="font-weight-semibold text-uppercase font-size-sm">Enter Project Plan information:</legend>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Select reference sources:</label>
                                <div class="col-md-6">
                                    @Html.DropDownListFor(x => x.SOURCEID, (IEnumerable<SelectListItem>)ViewBag.ListSource, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Select reference Project Type:</label>
                                <div class="col-md-6">
                                    @Html.DropDownListFor(x => x.PROJECT_TYPE, (IEnumerable<SelectListItem>)ViewBag.ListProjectType, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Plan name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.PLAN_NAME, new { @class = "form-control", @placeholder = "Plan Name" })
                                    <div class="form-control-feedback">
                                        <i id="projplanname-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.PLAN_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Description Plan name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.DESCRIPTION, new { @class = "form-control", @placeholder = "Enter your description Plan." })
                                    <div class="form-control-feedback">
                                        <i id="short-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-3 col-form-label">Enter remark:</label>
                                <div class="col-md-9 form-group-feedback-right">
                                    @Html.TextAreaFor(x => x.REMARK, new { @class = "form-control", @rows = "5", @cols = "5", @placeholder = "Enter your description here" })
                                    <div class="form-control-feedback">
                                        <i id="remark-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend></legend>
                            <div class="form-group row">
                                <div class="text-right col-md-12">
                                    <button type="submit" class="btn bg-teal">Submit form <i class="icon-paperplane ml-2"></i></button>
                                </div>
                            </div>
                        </fieldset>
                    }
                </div>
            </div>
            <!-- /form inputs -->
            <partial name="~/Views/Shared/_information_entry.cshtml" />
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ManagementProject/Views/ProjectPlans/Index.cshtml
@model IEnumerable<ManagementProject.Models.ProjectPlan>

<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">List Project Plans</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                <a class="list-icons-item" data-action="reload" asp-action="Index"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="float-right">
                    <button onclick="location.href='@Url.Action("Create","ProjectPlans")'"
                            class="ui-button jui-button bg-green border-green" data-fouc>
                        <i class="icon-plus3 mr-1"></i> New Project Plan
                    </button>
                </div>
            </div>
        </div>
        @using (Html.BeginForm())
        {
            <table class="table datatable-basic">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.PLAN_NAME)</th>
                        <th>@Html.DisplayNameFor(model => model.PROJECT_TYPE)</th>
                        <th>@Html.DisplayNameFor(model => model.SOURCEID)</th>
                        <th>@Html.DisplayNameFor(model => model.DESCRIPTION)</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.PLAN_NAME)</td>
                                <td>@Html.DisplayFor(modelItem => item.PROJECT_TYPE)</td>
                                <td>@Html.DisplayFor(modelItem => item.SOURCEID)</td>
                                <td>@Html.DisplayFor(modelItem => item.DESCRIPTION)</td>
                                <td class="text-center">
                                    <div class="list-icons">
                                        <div class="dropdown">
                                            <a href="#" class="list-icons-item" data-toggle="dropdown">
                                                <i class="icon-menu9"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href="@Url.Action("Edit","ProjectPlans",new { id = item.PROJECT_PLAN_ID})" class="dropdown-item">Edit <i class="fa fa-edit mr-1"></i></a>
                                                <a href="#modal_backdrop" id="mydel" data-toggle="modal" onclick="return getTitleRow(this);" class="dropdown-item">Delete <i class="icon-trash mr-1"></i></a>
                                           </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        }
    </div>
</div>
<script src="~/scripts/InternalCUD.js"></script>
<partial name="~/Views/Shared/_delete-screen.cshtml" />
<partial name="~/Views/Shared/_app-trans-message.cshtml" view-data="ViewData" />