ManagementProject/Controllers/ProjectTypesController.cs
using ManagementProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ManagementProject.Controllers
{
    public class ProjectTypesController : Controller
    {
        private readonly ManProContext _context;

        public ProjectTypesController(ManProContext context)
        {
            _context = context;
        }

        // GET: ProjectTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProjectType.ToListAsync());
        }

        // GET: ProjectTypes/Create
        public IActionResult Create()
        {
            ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");
            return View();
        }

        // POST: ProjectTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SOURCEID","PROJECT_TYPE,ABBREVIATION,LONG_NAME,SHORT_NAME,REMARK")] ProjectType projectType)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    projectType.ROW_CREATED_BY = "SYSTEM ADD";

                    _context.Add(projectType);
                    await _context.SaveChangesAsync();

                    TempData["resultTrans"] = new Dictionary<string, string>()
                    {
                        { "1", "0" },
                        { "2", "I" },
                        { "3", projectType.PROJECT_TYPE }
                    };

                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    TempData["resultTrans"] = new Dictionary<string, string>()
                    {
                        { "1", "1" },
                        { "2", "I" },
                        { "3", ex.Message }
                    };

                    ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");

                    return View();
                }
            }
            return View(projectType);
        }

        // GET: ProjectTypes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
                return NotFound();
            
            var projectType = await _context.ProjectType.FindAsync(id);

            if (projectType == null)
                return NotFound();

            ViewBag.ListSource = new SelectList(_context.Source.AsQueryable(), "SOURCEID", "ABBREVIATION");
 
            return View(projectType);
        }

        // POST: ProjectTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("PROJECT_TYPE,SOURCEID,ABBREVIATION,LONG_NAME,SHORT_NAME,REMARK")] ProjectType projectType)
        {
            if (id != projectType.PROJECT_TYPE)
                return NotFound();

            if (_context.ProjectType.Find(id) == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var local = _context.Set<ProjectType>()
                        .Local
                        .FirstOrDefault(x => x.PROJECT_TYPE.Equals(id));

                    local.SOURCEID = projectType.SOURCEID;
                    local.ABBREVIATION = projectType.ABBREVIATION;
                    local.LONG_NAME = projectType.LONG_NAME;
                    local.SHORT_NAME = projectType.SHORT_NAME;
                    local.REMARK = projectType.REMARK;

                    local.ROW_CHANGED_BY = "SYSTEM EDIT";

                    _context.Update(local);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectTypeExists(projectType.PROJECT_TYPE))
                        return NotFound();
                    else
                        throw;
                }

                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "0" },
                    { "2", "U" },
                    { "3", projectType.PROJECT_TYPE }
                };

                return RedirectToAction(nameof(Index));
            }
            return View(projectType);
        }

        // GET: ProjectTypes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "1" },
                    { "2", "D" },
                    { "3", $"Your parameter id is null." }
                };
                return View();
            }

            var projtype = await _context.ProjectType
                .FirstOrDefaultAsync(m => m.PROJECT_TYPE == id);

            if (projtype == null)
            {
                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "1" },
                    { "2", "D" },
                    { "3", $"ID key : {id}, not found." }
                };
                return View();
            }

            projtype = await _context.ProjectType.FindAsync(id);
            _context.ProjectType.Remove(projtype);
            await _context.SaveChangesAsync();

            TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "0" },
                    { "2", "D" },
                    { "3", projtype.PROJECT_TYPE }
                };

            return RedirectToAction(nameof(Index));
        }

        private bool ProjectTypeExists(string id)
        {
            return _context.ProjectType.Any(e => e.PROJECT_TYPE == id);
        }
    }
}

ManagementProject/Views/ProjectTypes/Create.cshtml
@model ManagementProject.Models.ProjectType
@{
    ViewData["Title"] = "Create";
    ViewData["PageType"] = "PROJECTTYPE";
}
<!-- Page content -->
<div class="page-content w-75">
    <!-- Main content -->
    <div class="content-wrapper">
        <!-- Content area -->
        <div class="content">
            <!-- Form inputs -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h5 class="card-title">Project Type form Input</h5>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="remove" asp-action="Index" asp-controller="ProjectTypes"></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Create", "ProjectTypes", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <fieldset>
                            <legend class="font-weight-semibold text-uppercase font-size-sm">Enter Project Type information:</legend>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Select reference sources:</label>
                                <div class="col-md-6">
                                    @Html.DropDownListFor(x => x.SOURCEID, (IEnumerable<SelectListItem>)ViewBag.ListSource, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Project Type name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.PROJECT_TYPE, new { @class = "form-control", @placeholder = "Project Type" })
                                    <div class="form-control-feedback">
                                        <i id="projtype-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.PROJECT_TYPE, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter abbreviation:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.ABBREVIATION, new { @class = "form-control", @placeholder = "Abbreviation" })
                                    <div class="form-control-feedback">
                                        <i id="abbr-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.ABBREVIATION, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter long name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.LONG_NAME, new { @class = "form-control", @placeholder = "Long Name" })
                                    <div class="form-control-feedback">
                                        <i id="long-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.LONG_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter short name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.SHORT_NAME, new { @class = "form-control", @placeholder = "Short Name" })
                                    <div class="form-control-feedback">
                                        <i id="short-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.SHORT_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-3 col-form-label">Enter remark:</label>
                                <div class="col-md-9 form-group-feedback-right">
                                    @Html.TextAreaFor(x => x.REMARK, new { @class = "form-control", @rows = "5", @cols = "5", @placeholder = "Enter your description here" })
                                    <div class="form-control-feedback">
                                        <i id="remark-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend></legend>
                            <div class="form-group row">
                                <div class="text-right col-md-12">
                                    <button type="submit" class="btn bg-teal">Submit form <i class="icon-paperplane ml-2"></i></button>
                                </div>
                            </div>
                        </fieldset>
                    }
                </div>
            </div>
            <!-- /form inputs -->
            <partial name="~/Views/Shared/_app-trans-message.cshtml" />
            <partial view-data="ViewData" name="~/Views/Shared/_information_entry.cshtml" />
        </div>
    </div>
</div>
<script src="~/scripts/InternalCUD.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ManagementProject/Views/ProjectTypes/Edit.cshtml
@model ManagementProject.Models.ProjectType
<!-- Page content -->
<div class="page-content w-75">
    <!-- Main content -->
    <div class="content-wrapper">
        <!-- Content area -->
        <div class="content">

            <!-- Form inputs -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h5 class="card-title">Project Type form Edit</h5>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="remove" asp-action="Index" asp-controller="ProjectTypes"></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Edit", "ProjectTypes", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <input type="hidden" asp-for="PROJECT_TYPE" />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <fieldset>
                            <legend class="font-weight-semibold text-uppercase font-size-sm">Enter Project Type information:</legend>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Select reference sources:</label>
                                <div class="col-md-6">
                                    @Html.DropDownListFor(model => model.SOURCEID, (IEnumerable<SelectListItem>)ViewBag.ListSource,null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter abbreviation:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.ABBREVIATION, new { @class = "form-control", @placeholder = "Abbreviation" })
                                    <div class="form-control-feedback">
                                        <i id="short-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.ABBREVIATION, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter long name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.LONG_NAME, new { @class = "form-control", @placeholder = "Long Name" })
                                    <div class="form-control-feedback">
                                        <i id="long-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.LONG_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter short name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.SHORT_NAME, new { @class = "form-control", @placeholder = "Short Name" })
                                    <div class="form-control-feedback">
                                        <i id="short-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.SHORT_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-3 col-form-label">Enter remark:</label>
                                <div class="col-md-9 form-group-feedback-right">
                                    @Html.TextAreaFor(x => x.REMARK, new { @class = "form-control", @rows = "5", @cols = "5", @placeholder = "Enter your description here" })
                                    <div class="form-control-feedback">
                                        <i id="remark-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend></legend>
                            <div class="form-group row">
                                <div class="text-right col-md-12">
                                    <button type="submit" class="btn bg-teal">Submit form <i class="icon-paperplane ml-2"></i></button>
                                </div>
                            </div>
                        </fieldset>
                    }
                </div>
            </div>
            <!-- /form inputs -->
            <partial name="~/Views/Shared/_information_entry.cshtml" />
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ManagementProject/Views/ProjectTypes/Index.cshtml
@model IEnumerable<ManagementProject.Models.ProjectType>

<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">List Project Type</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                <a class="list-icons-item" data-action="reload" asp-action="Index"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="float-right">
                    <button onclick="location.href='@Url.Action("Create","ProjectTypes")'"
                            class="ui-button jui-button bg-green border-green" data-fouc>
                        <i class="icon-plus3 mr-1"></i> New Project Type
                    </button>
                </div>
            </div>
        </div>
        @using (Html.BeginForm())
        {
            <table class="table datatable-basic">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.PROJECT_TYPE)</th>
                        <th>@Html.DisplayNameFor(model => model.ABBREVIATION)</th>
                        <th>@Html.DisplayNameFor(model => model.LONG_NAME)</th>
                        <th>@Html.DisplayNameFor(model => model.SHORT_NAME)</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.PROJECT_TYPE)</td>
                                <td>@Html.DisplayFor(modelItem => item.ABBREVIATION)</td>
                                <td>@Html.DisplayFor(modelItem => item.LONG_NAME)</td>
                                <td>@Html.DisplayFor(modelItem => item.SHORT_NAME)</td>
                                <td class="text-center">
                                    <div class="list-icons">
                                        <div class="dropdown">
                                            <a href="#" class="list-icons-item" data-toggle="dropdown">
                                                <i class="icon-menu9"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href="@Url.Action("Edit","ProjectTypes",new { id = item.PROJECT_TYPE})" class="dropdown-item">Edit <i class="fa fa-edit mr-1"></i></a>
                                                <a href="#modal_backdrop" id="mydel" data-toggle="modal" onclick="return getTitleRow(this);" class="dropdown-item">Delete <i class="icon-trash mr-1"></i></a>
                                                @Html.Hidden(item.PROJECT_TYPE) @Html.Hidden(Url.Action("Delete", "ProjectTypes", new { id = item.PROJECT_TYPE }))
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        }
    </div>
</div>
<script src="~/scripts/InternalCUD.js"></script>
<partial name="~/Views/Shared/_delete-screen.cshtml" />
<partial name="~/Views/Shared/_app-trans-message.cshtml" view-data="ViewData" />