ManagementProject/Models/ProjectPlanStep.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ManagementProject.Models
{
    [Table("PROJECT_PLAN_STEP")]
    public class ProjectPlanStep : Global
    {
        [Key]
        [Required]
        [StringLength(40, MinimumLength = 5)]
        [DisplayName("Plan Step ID")]
        public string PLAN_STEP_ID { get; set; }
        [ForeignKey("PROJECT_PLAN_ID")]
        [DisplayName("Plan ID")]
        public string PROJECT_PLAN_ID { get; set; }
        [Required]
        [StringLength(240, MinimumLength = 10)]
        [DisplayName("Description")]
        public string DESCRIPTION { get; set; }
        [Required]
        [StringLength(255, MinimumLength = 10)]
        [DisplayName("Step Name")]
        public string STEP_NAME { get; set; }
        [Required]
        [StringLength(240, MinimumLength = 10)]
        [DisplayName("Step Rule")]
        public string STEP_RULE { get; set; }
        [Required]
        [DefaultValue(true)]
        [DisplayName("Step Seq Number")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        public decimal STEP_SEQ_NO { get; set; }
        public string STEP_TYPE { get; set; }
    }
}

ManagementProject/Controllers/ProjectPlanStepsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ManagementProject.Models;

namespace ManagementProject.Controllers
{
    public class ProjectPlanStepsController : Controller
    {
        private readonly ManProContext _context;

        public ProjectPlanStepsController(ManProContext context)
        {
            _context = context;
        }

        // GET: ProjectPlanSteps
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProjectPlanStep.ToListAsync());
        }

        //// GET: ProjectPlan/Details/5
        //public JsonResult GetListProjPlan(string id)
        //{
        //    if (id == null)
        //        return Json("NotFound");

        //    var projectPlan = _context.ProjectPlan
        //        .Where(x => x.PROJECT_PLAN_ID == id)
        //        .Select( new { Prodid = x.p });
        //        //.FirstOrDefaultAsync(m => m.PROJECT_PLAN_ID == id);
        //    if (projectPlan== null)
        //        return Json("NotFound");

        //    return Json(projectPlan);
        //}

        // GET: ProjectPlanSteps/Create
        public IActionResult Create()
        {
            ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");
            ViewBag.ListProjectPlan = new SelectList(_context.ProjectPlan, "PROJECT_PLAN_ID", "PLAN_NAME");
            return View();
        }

        // POST: ProjectPlanSteps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PLAN_STEP_ID,PROJECT_PLAN_ID,DESCRIPTION,STEP_NAME,STEP_RULE,STEP_SEQ_NO,SOURCEID,ROW_CREATED_DATE")] ProjectPlanStep projectPlanStep)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    projectPlanStep.ROW_CREATED_BY = "SYSTEM ADD";

                    _context.Add(projectPlanStep);
                    await _context.SaveChangesAsync();

                    TempData["resultTrans"] = new Dictionary<string, string>()
                    {
                        { "1", "0" },
                        { "2", "I" },
                        { "3", projectPlanStep.PROJECT_PLAN_ID }
                    };

                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    TempData["resultTrans"] = new Dictionary<string, string>()
                    {
                        { "1", "1" },
                        { "2", "I" },
                        { "3", ex.Message }
                    };

                    ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");
                    ViewBag.ListProjectPlan = new SelectList(_context.ProjectPlan, "PROJECT_PLAN_ID", "PLAN_NAME");

                    return View();
                }
            }
            return View(projectPlanStep);
        }

        // GET: ProjectPlanSteps/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
                return NotFound();

            var projectPlanStep = await _context.ProjectPlanStep.FindAsync(id);
            if (projectPlanStep == null)
                return NotFound();

            ViewBag.ListSource = new SelectList(_context.Source, "SOURCEID", "ABBREVIATION");
            ViewBag.ListProjectPlan = new SelectList(_context.ProjectPlan, "PROJECT_PLAN_ID", "PLAN_NAME");

            return View(projectPlanStep);
        }

        // POST: ProjectPlanSteps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("PLAN_STEP_ID,PROJECT_PLAN_ID,DESCRIPTION,STEP_NAME,STEP_RULE,STEP_SEQ_NO,SOURCEID")] ProjectPlanStep projectPlanStep)
        {
            if (id != projectPlanStep.PLAN_STEP_ID)
                return NotFound();

            if (_context.ProjectPlanStep.Find(id) == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var local = _context.Set<ProjectPlanStep>()
                       .Local
                       .FirstOrDefault(x => x.PLAN_STEP_ID.Equals(id));

                    local.SOURCEID = projectPlanStep.SOURCEID;
                    local.PROJECT_PLAN_ID = projectPlanStep.PROJECT_PLAN_ID;
                    local.STEP_NAME = projectPlanStep.STEP_NAME;
                    local.STEP_RULE = projectPlanStep.STEP_RULE;
                    local.STEP_SEQ_NO = projectPlanStep.STEP_SEQ_NO;
                    local.DESCRIPTION = projectPlanStep.DESCRIPTION;

                    local.ROW_CHANGED_BY = "SYSTEM EDIT";

                    _context.Update(local);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectPlanStepExists(projectPlanStep.PLAN_STEP_ID))
                        return NotFound();
                    else
                        throw;
                }

                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "0" },
                    { "2", "U" },
                    { "3", projectPlanStep.PLAN_STEP_ID }
                };

                return RedirectToAction(nameof(Index));
            }
            return View(projectPlanStep);
        }

        // GET: ProjectPlanSteps/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "1" },
                    { "2", "D" },
                    { "3", $"Your parameter id is null." }
                };
                return View();
            }

            var projectPlanStep = await _context.ProjectPlanStep
                .FirstOrDefaultAsync(m => m.PLAN_STEP_ID == id);

            if (projectPlanStep == null)
            {
                TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "1" },
                    { "2", "D" },
                    { "3", $"ID key : {id}, not found." }
                };
                return View();
            }

            projectPlanStep = await _context.ProjectPlanStep.FindAsync(id);
            _context.ProjectPlanStep.Remove(projectPlanStep);
            await _context.SaveChangesAsync();

            TempData["resultTrans"] = new Dictionary<string, string>()
                {
                    { "1", "0" },
                    { "2", "D" },
                    { "3", projectPlanStep.PLAN_STEP_ID }
                };

            return RedirectToAction(nameof(Index));
        }

        private bool ProjectPlanStepExists(string id)
        {
            return _context.ProjectPlanStep.Any(e => e.PLAN_STEP_ID == id);
        }
    }
}

ManagementProject/Views/ProjectPlanSteps/Create.cshtml
@model ManagementProject.Models.ProjectPlanStep
<!-- Page content -->
<div class="page-content w-75">
    <!-- Main content -->
    <div class="content-wrapper">
        <!-- Content area -->
        <div class="content">
            <!-- Form inputs -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h5 class="card-title">Project Plan Step form Input</h5>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="remove" asp-action="Index" asp-controller="ProjectPlanSteps"></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Create", "ProjectPlanSteps", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <fieldset>
                            <legend class="font-weight-semibold text-uppercase font-size-sm">Enter Project Plan Step information:</legend>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Select reference sources:</label>
                                <div class="col-md-6">
                                    @Html.DropDownListFor(x => x.SOURCEID, (IEnumerable<SelectListItem>)ViewBag.ListSource, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Search Project Plan:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.DropDownListFor(x => x.PROJECT_PLAN_ID, (IEnumerable<SelectListItem>)ViewBag.ListProjectPlan, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Plan Step ID:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.PLAN_STEP_ID, new { @class = "form-control", @placeholder = "Plan Step ID" })
                                    <div class="form-control-feedback">
                                        <i id="planstepID-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.PLAN_STEP_ID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Plan Step name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.STEP_NAME, new { @class = "form-control", @placeholder = "Plan Step Name" })
                                    <div class="form-control-feedback">
                                        <i id="planstepName-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.STEP_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Plan Step Rule:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.STEP_RULE, new { @class = "form-control", @placeholder = "Plan Step Rule" })
                                    <div class="form-control-feedback">
                                        <i id="planstepRule-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.STEP_RULE, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Step seq Num:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.STEP_SEQ_NO, new { @class = "form-control", @placeholder = "Plan Step sequence Number", @type = "number", @min = "1", @value = "1" })
                                    <div class="form-control-feedback">
                                        <i id="planstepSeq-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.STEP_SEQ_NO, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Description:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextAreaFor(x => x.DESCRIPTION, new { @class = "form-control", @rows = "5", @cols = "5", @placeholder = "Enter your description Step" })
                                    <div class="form-control-feedback">
                                        <i id="projdesc-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend></legend>
                            <div class="form-group row">
                                <div class="text-right col-md-12">
                                    <button type="submit" class="btn bg-teal">Submit form <i class="icon-paperplane ml-2"></i></button>
                                </div>
                            </div>
                        </fieldset>
                    }
                </div>
            </div>
            <!-- /form inputs -->
            <partial name="~/Views/Shared/_app-trans-message.cshtml" />
            <partial view-data="ViewData" name="~/Views/Shared/_information_entry.cshtml" />
        </div>
    </div>
</div>
<script src="~/scripts/InternalCUD.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ManagementProject/Views/ProjectPlanSteps/Edit.cshtml
@model ManagementProject.Models.ProjectPlanStep
<!-- Page content -->
<div class="page-content w-75">
    <!-- Main content -->
    <div class="content-wrapper">
        <!-- Content area -->
        <div class="content">

            <!-- Form inputs -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h5 class="card-title">Project Plan form Edit</h5>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="remove" asp-action="Index" asp-controller="ProjectPlanSteps"></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Edit", "ProjectPlanSteps", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <input type="hidden" asp-format="" asp-for="PLAN_STEP_ID" />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <fieldset>
                            <legend class="font-weight-semibold text-uppercase font-size-sm">Enter Project Plan Step information:</legend>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Select reference sources:</label>
                                <div class="col-md-6">
                                    @Html.DropDownListFor(x => x.SOURCEID, (IEnumerable<SelectListItem>)ViewBag.ListSource, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Search Project Plan:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.DropDownListFor(x => x.PROJECT_PLAN_ID, (IEnumerable<SelectListItem>)ViewBag.ListProjectPlan, null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Plan Step ID:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.PLAN_STEP_ID, new { @class = "form-control", @placeholder = "Plan Step ID" })
                                    <div class="form-control-feedback">
                                        <i id="planstepID-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.PLAN_STEP_ID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Plan Step name:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.STEP_NAME, new { @class = "form-control", @placeholder = "Plan Step Name" })
                                    <div class="form-control-feedback">
                                        <i id="planstepName-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.STEP_NAME, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Plan Step Rule:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.STEP_RULE, new { @class = "form-control", @placeholder = "Plan Step Rule" })
                                    <div class="form-control-feedback">
                                        <i id="planstepRule-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.STEP_RULE, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Step seq Num:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextBoxFor(x => x.STEP_SEQ_NO, new { @class = "form-control", @placeholder = "Plan Step sequence Number", @type = "number", @min = "1" })
                                    <div class="form-control-feedback">
                                        <i id="planstepSeq-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.STEP_SEQ_NO, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Enter Description:</label>
                                <div class="col-md-6 form-group-feedback-right">
                                    @Html.TextAreaFor(x => x.DESCRIPTION, new { @class = "form-control", @rows = "5", @cols = "5", @placeholder = "Enter your description Step" })
                                    <div class="form-control-feedback">
                                        <i id="projdesc-inf-opener" title="Click for detail information" class="icon-question4"></i>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend></legend>
                            <div class="form-group row">
                                <div class="text-right col-md-12">
                                    <button type="submit" class="btn bg-teal">Submit form <i class="icon-paperplane ml-2"></i></button>
                                </div>
                            </div>
                        </fieldset>
                    }
                </div>
            </div>
            <!-- /form inputs -->
            <partial name="~/Views/Shared/_information_entry.cshtml" />
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ManagementProject/Views/ProjectPlanSteps/Index.cshtml
@model IEnumerable<ManagementProject.Models.ProjectPlanStep>

<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">List Project Plan Steps</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                <a class="list-icons-item" data-action="reload" asp-action="Index"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="float-right">
                    <button onclick="location.href='@Url.Action("Create","ProjectPlanSteps")'"
                            class="ui-button jui-button bg-green border-green" data-fouc>
                        <i class="icon-plus3 mr-1"></i> New Project Plan Step
                    </button>
                </div>
            </div>
        </div>
        @using (Html.BeginForm())
        {
            <table class="table datatable-basic">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.PLAN_STEP_ID)</th>
                        <th>@Html.DisplayNameFor(model => model.STEP_NAME)</th>
                        <th>@Html.DisplayNameFor(model => model.STEP_RULE)</th>
                        <th>@Html.DisplayNameFor(model => model.STEP_SEQ_NO)</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.PLAN_STEP_ID)</td>
                                <td>@Html.DisplayFor(modelItem => item.STEP_NAME)</td>
                                <td>@Html.DisplayFor(modelItem => item.STEP_RULE)</td>
                                <td>@Html.DisplayFor(modelItem => item.STEP_SEQ_NO)</td>
                                <td class="text-center">
                                    <div class="list-icons">
                                        <div class="dropdown">
                                            <a href="#" class="list-icons-item" data-toggle="dropdown">
                                                <i class="icon-menu9"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href="@Url.Action("Edit","ProjectPlanSteps",new { id = item.PLAN_STEP_ID})" class="dropdown-item">Edit <i class="fa fa-edit mr-1"></i></a>
                                                <a href="#modal_backdrop" id="mydel" data-toggle="modal" onclick="return getTitleRow(this);" class="dropdown-item">Delete <i class="icon-trash mr-1"></i></a>
                                                @Html.Hidden(item.PLAN_STEP_ID) @Html.Hidden(Url.Action("Delete", "ProjectPlanSteps", new { id = item.PLAN_STEP_ID }))

                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        }
    </div>
</div>
<script src="~/scripts/InternalCUD.js"></script>
<partial name="~/Views/Shared/_delete-screen.cshtml" />
<partial name="~/Views/Shared/_app-trans-message.cshtml" view-data="ViewData" />